In [1]:
import numpy as np

Criando uma array

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr
type(arr) #Mostra o tipo da variável

numpy.ndarray

Mostra a versão da library

In [4]:
np.__version__

'1.20.3'

Criando array com uma lista e um tuple

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = np.array((1, 2, 3, 4, 5))

Criando uma 0-D Array

In [6]:
arr = np.array(42)

arr

array(42)

1-D Array

In [ ]:
arr  = np.array([1, 2, 3, 4, 5])

arr

2-D Array

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

3-D Array

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Checando o número de dimensões

In [11]:
a = np.array(42)
b  = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions: 5
